<<<<<<< HEAD
CUDA_VISIBLE_DEVICES=0 python gene_completion/main.py --dataset villacampa_lung_organoid --autoencoder_ckpts_path /media/disk3/dvegaa/autoencoder/no_context/c_d_deltas/villacampa_lung_organoid/2025-06-16-15-32-51/autoencoder_model.ckpt --ae_input_dim 128
CUDA_VISIBLE_DEVICES=1 python gene_completion/main.py --dataset mirzazadeh_mouse_bone --autoencoder_ckpts_path /media/disk3/dvegaa/autoencoder/no_context/c_d_deltas/mirzazadeh_mouse_bone/2025-06-16-15-33-44/autoencoder_model.ckpt --ae_input_dim 128
CUDA_VISIBLE_DEVICES=0 python gene_completion/main.py --dataset abalo_human_squamous_cell_carcinoma --autoencoder_ckpts_path /media/disk3/dvegaa/autoencoder/no_context/c_d_deltas/abalo_human_squamous_cell_carcinoma/2025-06-16-15-48-12/autoencoder_model.ckpt --ae_input_dim 128
CUDA_VISIBLE_DEVICES=0 python gene_completion/main.py --dataset 10xgenomic_mouse_brain_sagittal_posterior --autoencoder_ckpts_path /media/SSD4/dvegaa/autoencoder/no_context/c_d_deltas/10xgenomic_mouse_brain_sagittal_posterior/2025-06-09-17-46-02/autoencoder_model.ckpt --input_dim 128
CUDA_VISIBLE_DEVICES=0 python gene_completion/main.py --dataset villacampa_mouse_brain --autoencoder_ckpts_path /media/SSD4/dvegaa/autoencoder/no_context/c_d_deltas/villacampa_mouse_brain/2025-06-10-12-40-41/autoencoder_model.ckpt --ae_input_dim 32 --ae_latent_dim 32
CUDA_VISIBLE_DEVICES=0 python gene_completion/main.py --dataset vicari_human_striatium --autoencoder_ckpts_path /media/SSD4/dvegaa/autoencoder/no_context/c_d_deltas/vicari_human_striatium/2025-06-10-12-39-45/autoencoder_model.ckpt --ae_input_dim 32 --ae_latent_dim 32
=======
CUDA_VISIBLE_DEVICES=0 python main.py --dataset villacampa_lung_organoid --autoencoder_ckpts_path /media/SSD4/dvegaa/autoencoder/no_context/c_d_deltas/villacampa_lung_organoid/2025-06-11-22-05-09/autoencoder_model.ckpt --ae_input_dim 128
CUDA_VISIBLE_DEVICES=1 python main.py --dataset 10xgenomic_mouse_brain_sagittal_posterior --autoencoder_ckpts_path /media/SSD4/dvegaa/autoencoder/no_context/c_d_deltas/10xgenomic_mouse_brain_sagittal_posterior/2025-06-11-16-45-24/autoencoder_model.ckpt --ae_input_dim 128
CUDA_VISIBLE_DEVICES=2 python main.py --dataset mirzazadeh_mouse_bone --autoencoder_ckpts_path /media/SSD4/dvegaa/autoencoder/no_context/c_d_deltas/mirzazadeh_mouse_bone/2025-06-11-18-10-45/autoencoder_model.ckpt --ae_input_dim 128
CUDA_VISIBLE_DEVICES=3 python main.py --dataset abalo_human_squamous_cell_carcinoma --autoencoder_ckpts_path /media/SSD4/dvegaa/autoencoder/no_context/c_d_deltas/abalo_human_squamous_cell_carcinoma/2025-06-11-19-52-12/autoencoder_model.ckpt --ae_input_dim 128
CUDA_VISIBLE_DEVICES=4 python main.py --dataset villacampa_mouse_brain --autoencoder_ckpts_path /media/SSD4/dvegaa/autoencoder/no_context/c_d_deltas/villacampa_mouse_brain/2025-06-12-02-18-02/autoencoder_model.ckpt --ae_input_dim 32 --ae_latent_dim 32
CUDA_VISIBLE_DEVICES=5 python main.py --dataset vicari_human_striatium --autoencoder_ckpts_path /media/SSD4/dvegaa/autoencoder/no_context/c_d_deltas/vicari_human_striatium/2025-06-11-22-25-12/autoencoder_model.ckpt --ae_input_dim 32 --ae_latent_dim 32
>>>>>>> 89af05dd5edaa2bde1e3d08119dcbd6ed5b71cd2
